# syntax=docker/dockerfile:1

FROM node:22-slim AS frontend

WORKDIR /app

COPY package*.json ./
RUN npm config set registry https://registry.npmmirror.com \
 && npm install --force \
 && npm cache clean --force

# Copy the rest of the frontend sources
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]
